apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sepa-spikes
  annotations:
    github.com/project-slug: cpiemontese/sepa-spikes
spec:
  type: other
  lifecycle: unknown
  owner: team-shared-services
